//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int ID { get; set; }
        public string CommentText { get; set; }
        public string UserId { get; set; }
        public int TaskId { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
