//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks()
        {
            this.Attachments = new HashSet<Attachments>();
            this.Comments = new HashSet<Comments>();
            this.Tasks1 = new HashSet<Tasks>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> ScheduledTime { get; set; }
        public string ResponsibleUserId { get; set; }
        public string AssignedUserId { get; set; }
        public int CurrentStatusId { get; set; }
        public int TaskPriorityId { get; set; }
        public Nullable<int> ResultId { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> ParentTaskId { get; set; }
        public int TaskTypeId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public bool isTemplate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachments> Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual Results Results { get; set; }
        public virtual TaskPriorities TaskPriorities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasks> Tasks1 { get; set; }
        public virtual Tasks Tasks2 { get; set; }
        public virtual TaskStatuses TaskStatuses { get; set; }
        public virtual TaskTypes TaskTypes { get; set; }
    }
}
